// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUwL3V6MT7EDVAT2dijd3c2PjRhszvsBc',
    appId: '1:442433464342:web:445bd756a8f17cb95c2d37',
    messagingSenderId: '442433464342',
    projectId: 'movirate-akjpro',
    authDomain: 'movirate-akjpro.firebaseapp.com',
    storageBucket: 'movirate-akjpro.firebasestorage.app',
    measurementId: 'G-LHELRPR33S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAekMkC3kiESJoDqVhG-cvxUSZovDziqHE',
    appId: '1:442433464342:android:78e7e69c5f5ec2525c2d37',
    messagingSenderId: '442433464342',
    projectId: 'movirate-akjpro',
    storageBucket: 'movirate-akjpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvzg_NNfeqZdSjJUENXK0sUoqHCftmRn4',
    appId: '1:442433464342:ios:04df7b73b98dad3b5c2d37',
    messagingSenderId: '442433464342',
    projectId: 'movirate-akjpro',
    storageBucket: 'movirate-akjpro.firebasestorage.app',
    iosBundleId: 'com.akjpro.movirate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUwL3V6MT7EDVAT2dijd3c2PjRhszvsBc',
    appId: '1:442433464342:web:ba87d7c0e3e1bc1f5c2d37',
    messagingSenderId: '442433464342',
    projectId: 'movirate-akjpro',
    authDomain: 'movirate-akjpro.firebaseapp.com',
    storageBucket: 'movirate-akjpro.firebasestorage.app',
    measurementId: 'G-ZJXVR7EG9B',
  );
}
